import base64
import math
import os

import cv2
import joblib
import numpy as np
import mediapipe as mp
from mediapipe.tasks import python as mp_python
from mediapipe.tasks.python import vision as mp_vision
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_methods=["*"],
    allow_headers=["*"],
)

sessions = []

# ── MediaPipe PoseLandmarker (loaded once) ─────────────────────────────────────
_BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
_POSE_MODEL  = os.path.join(_BASE_DIR, "pose_landmarker_lite.task")
_base_options = mp_python.BaseOptions(model_asset_path=_POSE_MODEL)
_pose_options = mp_vision.PoseLandmarkerOptions(
    base_options=_base_options,
    running_mode=mp_vision.RunningMode.IMAGE,
)
pose_landmarker = mp_vision.PoseLandmarker.create_from_options(_pose_options)

_LEFT_HIP   = 23
_LEFT_KNEE  = 25
_LEFT_ANKLE = 27

# ── ML quality model (loaded once, None if not yet trained) ───────────────────
_ML_MODEL_PATH = os.path.join(_BASE_DIR, "ml", "model.pkl")
try:
    ml_model = joblib.load(_ML_MODEL_PATH)
    print(f"ML model loaded from {_ML_MODEL_PATH}")
except FileNotFoundError:
    ml_model = None
    print("ML model not found — run ml/train_model.py to train it")


class SessionData(BaseModel):
    date: str
    reps: int
    max_angle: float
    quality_score: float
    pain_level: int


class MLScoreInput(BaseModel):
    max_angle: float
    rep_duration: float
    knee_wobble: float


class AnalyzeInput(BaseModel):
    frame: str


# Health check — confirms the API is reachable
@app.get("/")
def root():
    return {"status": "ok", "message": "Rehab API running"}


# Persists a completed rehab session to the in-memory sessions list
@app.post("/session/save")
def save_session(data: SessionData):
    sessions.append(data.dict())
    return {"saved": True}


# Returns all previously saved rehab sessions
@app.get("/session/history")
def session_history():
    return sessions


# Scores rep quality using the trained RandomForest model
@app.post("/ml/score")
def ml_score(data: MLScoreInput):
    if ml_model is None:
        return {"error": "Model not trained yet. Run ml/train_model.py first"}

    features = [[data.max_angle, data.rep_duration, data.knee_wobble]]
    prediction = ml_model.predict(features)[0]
    proba      = ml_model.predict_proba(features)[0]

    # proba[0] = P(poor), proba[1] = P(good)
    confidence = float(max(proba))
    score      = float(proba[1])   # probability of "good" — used as quality_score 0–1

    return {
        "quality":    "good" if int(prediction) == 1 else "poor",
        "confidence": round(confidence, 3),
        "score":      round(score, 3),
    }


# Serves the feature importance PNG generated by ml/train_model.py
@app.get("/ml/feature-importance")
def feature_importance():
    path = os.path.join(_BASE_DIR, "ml", "feature_importance.png")
    if not os.path.exists(path):
        return {"error": "Feature importance chart not found. Run ml/train_model.py first"}
    return FileResponse(path, media_type="image/png")


# Serves the AUC-ROC curve PNG generated by ml/train_model.py
@app.get("/ml/roc-curve")
def roc_curve_image():
    path = os.path.join(_BASE_DIR, "ml", "roc_curve.png")
    if not os.path.exists(path):
        return {"error": "ROC curve not found. Run ml/train_model.py first"}
    return FileResponse(path, media_type="image/png")


# Runs MediaPipe PoseLandmarker on a base64 JPEG frame; returns knee angle + feedback
@app.post("/analyze")
def analyze(data: AnalyzeInput):
    # Decode base64 → bytes → numpy array → OpenCV BGR image
    img_bytes = base64.b64decode(data.frame)
    arr = np.frombuffer(img_bytes, dtype=np.uint8)
    img = cv2.imdecode(arr, cv2.IMREAD_COLOR)
    if img is None:
        return {"angle": 0, "landmarks": None, "feedback": "Invalid frame"}

    h, w, _ = img.shape
    rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb)
    result   = pose_landmarker.detect(mp_image)

    if not result.pose_landmarks:
        return {"angle": 0, "landmarks": None, "feedback": "No pose detected"}

    lm    = result.pose_landmarks[0]
    hip   = lm[_LEFT_HIP]
    knee  = lm[_LEFT_KNEE]
    ankle = lm[_LEFT_ANKLE]

    # Normalized coords → pixel space for stable angle calculation
    hip_px   = (hip.x * w,   hip.y * h)
    knee_px  = (knee.x * w,  knee.y * h)
    ankle_px = (ankle.x * w, ankle.y * h)

    # Vectors from knee toward hip and ankle
    v1 = (hip_px[0]   - knee_px[0], hip_px[1]   - knee_px[1])
    v2 = (ankle_px[0] - knee_px[0], ankle_px[1] - knee_px[1])

    angle = math.degrees(
        math.atan2(v2[1], v2[0]) - math.atan2(v1[1], v1[0])
    )
    angle = abs(angle)
    if angle > 180:
        angle = 360 - angle

    if angle > 160:
        feedback = "Good extension!"
    elif angle < 100:
        feedback = "Bend your knee"
    else:
        feedback = "Hold..."

    landmarks = {
        "hip":   {"x": round(hip.x, 4),   "y": round(hip.y, 4)},
        "knee":  {"x": round(knee.x, 4),  "y": round(knee.y, 4)},
        "ankle": {"x": round(ankle.x, 4), "y": round(ankle.y, 4)},
    }

    return {"angle": round(angle, 2), "landmarks": landmarks, "feedback": feedback}
